Khabari/Areas/Administration/Pages/News/NewsCategory/Create.cshtml.cs
using _0_Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NewsManagement.Application.Contracts.NewsCategory;

namespace Khabari.Areas.Administration.Pages.News.NewsCategory
{
    public class CreateModel : PageModel
    {
        public CreateNewsCategory createNewsCategory;
        private readonly INewsCategoryApplication _newsCategoryApplication;

        public CreateModel(INewsCategoryApplication newsCategoryApplication)
        {
            _newsCategoryApplication = newsCategoryApplication;
        }

        public void OnGet()
        {

        }
        public IActionResult OnPost(CreateNewsCategory createNewsCategory) 
        {
           OperationResult operation= _newsCategoryApplication.Create(createNewsCategory);
            return RedirectToPage("./Index");
        }

    }
}

Khabari/Areas/Administration/Pages/News/NewsCategory/Edit.cshtml.cs
using _0_Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NewsManagement.Application.Contracts.NewsCategory;

namespace Khabari.Areas.Administration.Pages.News.NewsCategory
{
    public class EditModel : PageModel
    {
        public EditNewsCategory editNewsCategory { get; set; }

        private readonly INewsCategoryApplication _newsCategoryApplication;

        public EditModel(INewsCategoryApplication newsCategoryApplication)
        {
            _newsCategoryApplication = newsCategoryApplication;
        }

        public void OnGet(long id)
        {
           editNewsCategory= _newsCategoryApplication.GetDetails(id);
        }
        public IActionResult OnPost(EditNewsCategory editNewsCategory)
        {
            OperationResult operation = _newsCategoryApplication.Edit(editNewsCategory);
            return RedirectToPage("./Index");
        }
    }
}

Khabari/Areas/Administration/Pages/News/NewsCategory/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NewsManagement.Application.Contracts.NewsCategory;
using System.Xml.Schema;

namespace Khabari.Areas.Administration.Pages.News.NewsCategory
{
    public class IndexModel : PageModel
    {
        private readonly INewsCategoryApplication _newsCategoryApplication;
        public NewsCategorySearchModel searchModel;
        public List<NewsCategoryViewModel> newsCategories;

        public IndexModel(INewsCategoryApplication newsCategoryApplication)
        {
            _newsCategoryApplication = newsCategoryApplication;
        }

        public void OnGet()
        {
            newsCategories = _newsCategoryApplication.List();
        }
    }
}

Khabari/Areas/Administration/Pages/News/OneNews/Create.cshtml.cs
using _0_Framework.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewsManagement.Application.Contracts.NewsCategory;
using NewsManagement.Application.Contracts.OneNews;

namespace Khabari.Areas.Administration.Pages.News.OneNews
{
    public class CreateModel : PageModel
    {
        private readonly IOneNewsApplication _oneNewsApplication;
        
        private readonly INewsCategoryApplication _newsCategoryApplication;
        public CreateOneNews CreateOneNews ;
        public SelectList newsCategory;

        public CreateModel(IOneNewsApplication oneNewsApplication, IFileUploader fileUploader, INewsCategoryApplication newsCategoryApplication)
        {
            _oneNewsApplication = oneNewsApplication;
           
            _newsCategoryApplication = newsCategoryApplication;
        }

        public void OnGet()
        {
            newsCategory = new SelectList(_newsCategoryApplication.List(), "Id", "Name");
        }
        public IActionResult OnPost(CreateOneNews createOneNews)
        {
            _oneNewsApplication.Create(createOneNews);

            return RedirectToPage("Index");
        }
    }
}

Khabari/Areas/Administration/Pages/News/OneNews/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewsManagement.Application;
using NewsManagement.Application.Contracts.NewsCategory;
using NewsManagement.Application.Contracts.OneNews;

namespace Khabari.Areas.Administration.Pages.News.OneNews
{
    public class EditModel : PageModel
    {
        private readonly IOneNewsApplication _oneNewsApplication;
        private readonly INewsCategoryApplication _newsCategoryApplication;  
        public EditOneNews editOneNews { get; set; }
        public SelectList newsCategory;
        public EditModel(IOneNewsApplication oneNewsApplication,
            INewsCategoryApplication newsCategoryApplication)
        {
            _oneNewsApplication = oneNewsApplication;
            _newsCategoryApplication = newsCategoryApplication;
        }
        public void OnGet(int id)
        {
            editOneNews=_oneNewsApplication.GetDetails(id);
            newsCategory= new SelectList(_newsCategoryApplication.List(), "Id", "Name");
        }
        public IActionResult OnPost(EditOneNews editOneNews)
        {
            _oneNewsApplication.Edit(editOneNews);
            return RedirectToPage("Index");
        }
    }
}

Khabari/Areas/Administration/Pages/News/OneNews/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NewsManagement.Application.Contracts.OneNews;
using NewsManagement.Domain;

namespace Khabari.Areas.Administration.Pages.News.OneNews
{
    public class IndexModel : PageModel
    {
        private readonly IOneNewsApplication _oneNewsApplication;
        public OneNewsSearchModel searchModel;
        public List<OneNewsViewModel> oneNews;
        public EditOneNews News;
        public IndexModel(IOneNewsApplication oneNewsApplication)
        {
            _oneNewsApplication = oneNewsApplication;
        }

        public void OnGet()
        {
            oneNews = _oneNewsApplication.List();
        }
        public IActionResult OnGetPublish(int id)
        {
          News=_oneNewsApplication.GetDetails(id);
            
            if(News.IsPublished)
            {
                News.IsPublished = false;
            }
            else
            {
                News.IsPublished = true;
            }
            
            _oneNewsApplication.Edit(News);
            return RedirectToPage("Index");
        }
        public IActionResult OnGetDelete(int id)
        {
            News = _oneNewsApplication.GetDetails(id);
            _oneNewsApplication.Delete(News);
            
            return RedirectToPage("Index");

        }
    }
}

Khabari/Areas/Administration/Pages/News/OneNews/Create.cshtml
@page
@model Khabari.Areas.Administration.Pages.News.OneNews.CreateModel
@{
}
<form method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">

            <div class="d-flex justify-content-center info-profile mt-2">
                <label class="filebutton">

                    <span><input type="file" asp-for="CreateOneNews.Picture" accept="image/*"></span>
                </label>
            </div>
            <div class="col-12 d-flex justify-content-center">
                <small class="text-center">تصویر خبر را آپلود کنید</small>

            </div>


            <div class="form-group">
                <label class="" asp-for="CreateOneNews.NewsCategoryId"> گروه اخبار</label>
                <select class="form-control" asp-for="CreateOneNews.NewsCategoryId" asp-items="Model.newsCategory">
                    <option value="0">انتخاب گروه اخبار </option>
                </select>
                <span asp-validation-for="CreateOneNews.NewsCategoryId" class="error"></span>
            </div>


            <div class="col-md-6">
                <div class="form-group">
                    <label for="Name" class="control-label">عنوان</label>
                    <input type="text" class="form-control"  asp-for="CreateOneNews.Subject" onchange="makeSlug('Name', 'Slug')">
                    <span asp-validation-for="CreateOneNews.Subject" class="error"></span>
                </div>
            </div>

        </div>


        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label for="Description" class="control-label">متن خبر</label>
                    <textarea class="form-control autogrow"  asp-for="CreateOneNews.Body"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="CreateOneNews.Body" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label for="Description" class="control-label">تاریخ انتشار</label>
                    <textarea class="form-control autogrow"  asp-for="CreateOneNews.PublishDate"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="CreateOneNews.PublishDate" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label for="Description" class="control-label">تگ</label>
                    <textarea class="form-control autogrow"  asp-for="CreateOneNews.Tag"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="CreateOneNews.Tag" class="error"></span>
                </div>
            </div>
        </div>

        



    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

Khabari/Areas/Administration/Pages/News/OneNews/Edit.cshtml
@page
@model Khabari.Areas.Administration.Pages.News.OneNews.EditModel
@{
}
<form method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">

            <div class="d-flex justify-content-center info-profile mt-2">
                <label class="filebutton">

                    <span><input type="file" asp-for="editOneNews.Picture" accept="image/*"></span>
                </label>
            </div>
            <div class="col-12 d-flex justify-content-center">
                <small class="text-center">تصویر خبر را آپلود کنید</small>

            </div>


            <div class="form-group">
                <label class="" asp-for="editOneNews.NewsCategoryId"> گروه اخبار</label>
                <select class="form-control" asp-for="editOneNews.NewsCategoryId" asp-items="Model.newsCategory">
                    <option value="0">انتخاب گروه اخبار </option>
                </select>
                <span asp-validation-for="editOneNews.NewsCategoryId" class="error"></span>
            </div>


            <div class="col-md-6">
                <div class="form-group">
                    <label for="Name" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="editOneNews.Subject" onchange="makeSlug('Name', 'Slug')">
                    <input type="text" class="form-control"  asp-for="editOneNews.Id">
                    <input type="text" class="form-control"  asp-for="editOneNews.PictureTemp">
                    <span asp-validation-for="editOneNews.Subject" class="error"></span>
                </div>
            </div>

        </div>


        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label for="Description" class="control-label">متن خبر</label>
                    <textarea class="form-control autogrow" asp-for="editOneNews.Body"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="editOneNews.Body" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label for="Description" class="control-label">تاریخ انتشار</label>
                    <textarea class="form-control autogrow" asp-for="editOneNews.PublishDate"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="editOneNews.PublishDate" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label for="Description" class="control-label">تگ</label>
                    <textarea class="form-control autogrow" asp-for="editOneNews.Tag"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="editOneNews.Tag" class="error"></span>
                </div>
            </div>
        </div>





    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

Khabari/Areas/Administration/Pages/News/OneNews/Index.cshtml
@page
@model Khabari.Areas.Administration.Pages.News.OneNews.IndexModel
@{
}


<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            @* <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد گروه محصول جدید</a>*@
            <a class="btn btn-success btn-lg" asp-page="./Create" asp-area="Administration">ایجاد خبر</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در گروه اخبار</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="searchModel.Subject"></label>
                        <input class="form-control" asp-for="searchModel.CategoryId" placeholder="نام گروه اخبار">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست گروه اخبار</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                     <th>عکس</th>
                                    <th>عنوان</th>
                                    @* <th>ترتیب نمایش</th>*@
                                    <th>تاریخ تولید</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.oneNews)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                    <img src="~/Images/@item.Picture" style="width: 70px; height: 70px" />
                                    </td>
                                       
                                        <td>@item.Subject</td>
                                        <td>@item.PublishDate</td>
                                        <td>@item.IsPublished</td>
                                        <td>@item.Tag</td>
                                        

                                        <td>
                                            @*<a class="btn btn-warning pull-right m-rl-5"
                                        href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                        <i class="fa fa-edit"></i> ویرایش
                                        </a>*@
                                            <a class="btn btn-warning pull-right m-rl-5"
                                           asp-page="./Edit" asp-route-id="@item.Id">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>

                                            <a class="btn btn-warning pull-right m-rl-5"
                                           asp-page-handler="Publish" asp-route-id="@item.Id">
                                                <i class="fa fa-edit"></i> انتشار
                                            </a>
                                            <a class="btn btn-warning pull-right m-rl-5"
                                           asp-page-handler="Delete" asp-route-id="@item.Id">
                                                <i class="fa fa-trash"></i> حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });

    </script>
}