Khabari/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Khabari.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Khabari/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Khabari.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Khabari/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Khabari.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Khabari/ViewComponets/LatestNewsViewComponent.cs
using _1_KhabariQuery.Contracts.OneNews;
using _1_KhabariQuery.Query;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Khabari.ViewComponets
{
    public class LatestNewsViewComponent:ViewComponent
    {
        private readonly IOneNewsQuery _oneNewsQuery;

        public LatestNewsViewComponent(IOneNewsQuery oneNewsQuery)
        {
            _oneNewsQuery = oneNewsQuery;
        }

        public IViewComponentResult Invoke()
        {
            var Onenews = _oneNewsQuery.GetAll();
            return View(Onenews);
        }

        
    }
}

Khabari/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html>

<body id="home">

    

   


    <section class="container mt-2">
        <div class="row">
            <div class="col-lg-3 pt-1 order-lg-1 order-2 text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-6 mb-3">
                            <a href="#"><img src="~/KhabariTheme/Images/banner1-min-1.png " class="img-fluid rad12"></a>
                        </div>
                        <div class="col-lg-12 col-6 mb-3">
                            <a href="#"><img src="~/KhabariTheme/Images/banner1-min-3.png " class="img-fluid rad12"></a>
                        </div>
                        <div class="col-lg-12 col-6 mb-3">
                            <a href="#"><img src="~/KhabariTheme/Images/banner1-min-2.png " class="img-fluid rad12"></a>
                        </div>
                        <div class="col-lg-12 col-6 mb-2">
                            <a href="#"><img src="~/KhabariTheme/Images/banner1-min-4.png " class="img-fluid rad12"></a>
                        </div>
                        <img src="~/KhabariTheme/Images/foot.png" class="mx-auto text-center" />

                    </div>
                </div>

            </div>
            <div class="col-lg-9 mb-lg-0 mb-3 order-lg-2  order-1">
                <div id="owl-slider" class="owl-carousel">
                    <div class="item">
                        <a href="#">
                            <img src="~/KhabariTheme/Images/Slides/Slide-1.png" alt="slide1" class="img-fluid" />
                            <div class="caption"><p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p></div>
                        </a>
                    </div>
                    <div class="item">
                        <a href="#">
                            <img src="~/KhabariTheme/Images/Slides/Slide-2.png" alt="slide2" class="img-fluid" />
                            <div class="caption"><p>لورم ایپسوم از صنعت چاپ و با استفاده از طراحان </p></div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <section class="container mt-4 text-center">
        <h5 class="IRANSansWeb_Medium  bt-color">خدمات ما</h5>
        <p>کلیه خدمات قابل ارائه لورم ایپسوم از صنعت چاپ </p>
        <div id="owl-Service" class="owl-carousel">
            <div class="card mx-1">
                <div class="card-body">
                    <a href="#">
                        <img class="rounded-circle" src="~/KhabariTheme/Images/11.jpg" alt="">
                    </a>
                    <h6>عنوان یک</h6>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
                    <a href="#" class="btn btn-grad px-5 text-white mt-3 rad25">مشاهده</a>
                </div>
            </div>
            <div class="card mx-1">
                <div class="card-body">
                    <a href="#">
                        <img class="rounded-circle" src="~/KhabariTheme/Images/12.jpg" alt="">
                    </a>
                    <h6>عنوان دو</h6>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
                    <a href="#" class="btn btn-grad px-5 text-white mt-3 rad25">مشاهده</a>
                </div>
            </div>
            <div class="card mx-1">
                <div class="card-body">
                    <a href="#">
                        <img class="rounded-circle" src="~/KhabariTheme/Images/11.jpg" alt="">
                    </a>
                    <h6>عنوان سه</h6>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
                    <a href="#" class="btn btn-grad px-5 text-white mt-3 rad25">مشاهده</a>
                </div>
            </div>
            <div class="card mx-1">
                <div class="card-body">
                    <a href="#">
                        <img class="rounded-circle" src="~/KhabariTheme/Images/14.jpg" alt="">
                    </a>
                    <h6>عنوان چهار</h6>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
                    <a href="#" class="btn btn-grad px-5 text-white mt-3 rad25">مشاهده</a>
                </div>
            </div>
            <div class="card mx-1">
                <div class="card-body">
                    <a href="#">
                        <img class="rounded-circle" src="~/KhabariTheme/Images/16.jpg" alt="">
                    </a>
                    <h6>عنوان پنج</h6>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
                    <a href="#" class="btn btn-grad px-5 text-white mt-3 rad25">مشاهده</a>
                </div>
            </div>
            <div class="card mx-1">
                <div class="card-body">
                    <a href="#">
                        <img class="rounded-circle" src="~/KhabariTheme/Images/12.jpg" alt="">
                    </a>
                    <h6>عنوان شش</h6>
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
                    <a href="#" class="btn btn-grad px-5 text-white mt-3 rad25">مشاهده</a>
                </div>
            </div>

        </div>

    </section>


    @await Component.InvokeAsync("LatestNews")
   @* <partial name="temp" model="" />*@

    <section class="container mt-4 mb-5">
        <div id="foottop" class="row p-3 mx-2 mt-2 grad-bg text-center text-white rad25">
            <div class="col-lg-4">
                <a href="#"><img src="~/KhabariTheme/Images/logo2.png" /></a>
            </div>
            <div class="col-lg-8">
                <h6 class="mb-2 IRANSansWeb_Medium">شماره های تماس :</h6>
                <a href="#" class="rounded-btn text-white text-center support-phone IRANSansWeb_Bold">01733265147 __ 01733265149</a>
            </div>
        </div>
        <img src="~/KhabariTheme/Images/foot.png" class="float-left ml-5" />
    </section>


    <section class="container text-center pt-4 mt-5">
        <h5 class="IRANSansWeb_Medium bt-color">نمایندگان ما</h5>
        <p>جهت مشاهده همکاران ما در شهر خود از لینک های زیر استفاده نمایید</p>
        <div id="owl-province" class="owl-carousel">
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/17.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/18.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/17.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/18.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/17.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/18.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/17.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>
            <div class="card mx-2">
                <a href="#">
                    <img src="~/KhabariTheme/Images/18.jpg" class="rad25" />
                    <p class="IRANSansWeb_Medium pt-2">لورم ایپسوم</p>
                </a>
            </div>

        </div>

    </section>


   

</body>
</html>